### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by smetj** [smetj/wishbone#7]
```
Traceback (most recent call last):
  File "/home/smetj/data/python/virtualenv/pypy/site-packages/gevent-1.1rc4-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 522, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/smetj/data/python/virtualenv/pypy/site-packages/wishbone-2.1.1-py2.7.egg/wishbone/actor.py", line 210, in __consumer
    function(event)
  File "/home/smetj/data/python/virtualenv/pypy/site-packages/wishbone-2.1.1-py2.7.egg/wishbone/module/stdout.py", line 128, in consume
    self.kwargs.prefix, self.format.do(event)))
RuntimeError: maximum recursion depth exceeded
<Greenlet at 0x7fb33d4471f0L: <bound method STDOUT.__consumer of <wishbone.module.stdout.STDOUT instance at 0x00007fb33d2e4a60>>(<bound method STDOUT.consume of <wishbone.module.s, 'inbox')> failed with RuntimeError

```

**Comment by smetj** [comment]
Was a pypy error. Solved with pypy-5
