### ISSUE TITLE
wishbone.lookup.randomword problem 2.7 vs 3.5 

### ISSUE THREAD

**Issue by smetj** [smetj/wishbone#9]
```
Instance started in foreground with pid 17087
Traceback (most recent call last):
  File "/home/smetj/data/python/virtualenv/wishbone/bin/wishbone", line 9, in <module>
    load_entry_point('wishbone==2.2.0', 'console_scripts', 'wishbone')()
  File "/home/smetj/data/python/virtualenv/wishbone/lib/python2.7/site-packages/wishbone-2.2.0-py2.7.egg/wishbone/bootstrap.py", line 277, in main
    BootStrap()
  File "/home/smetj/data/python/virtualenv/wishbone/lib/python2.7/site-packages/wishbone-2.2.0-py2.7.egg/wishbone/bootstrap.py", line 95, in __init__
    getattr(dispatch, arguments["command"])(**arguments)
  File "/home/smetj/data/python/virtualenv/wishbone/lib/python2.7/site-packages/wishbone-2.2.0-py2.7.egg/wishbone/bootstrap.py", line 144, in debug
    Default(router_config, module_manager, size=queue_size, frequency=frequency, identification=identification, stdout_logging=True, graph=graph, graph_include_sys=graph_include_sys).start()
  File "/home/smetj/data/python/virtualenv/wishbone/lib/python2.7/site-packages/wishbone-2.2.0-py2.7.egg/wishbone/router/default.py", line 143, in start
    self.__start()
  File "/home/smetj/data/python/virtualenv/wishbone/lib/python2.7/site-packages/wishbone-2.2.0-py2.7.egg/wishbone/router/default.py", line 238, in __start
    self.__initConfig()
  File "/home/smetj/data/python/virtualenv/wishbone/lib/python2.7/site-packages/wishbone-2.2.0-py2.7.egg/wishbone/router/default.py", line 189, in __initConfig
    lookup_modules[name] = self.__registerLookupModule(instance.module, **instance.arguments)
  File "/home/smetj/data/python/virtualenv/wishbone/lib/python2.7/site-packages/wishbone-2.2.0-py2.7.egg/wishbone/router/default.py", line 220, in __registerLookupModule
    return getattr(m, function)(**kwargs)
  File "/home/smetj/data/python/virtualenv/wishbone/lib/python2.7/site-packages/wishbone-2.2.0-py2.7.egg/wishbone/lookup/__init__.py", line 215, in randomword
    return RandomWord(filename).pickWord
  File "/home/smetj/data/python/virtualenv/wishbone/lib/python2.7/site-packages/wishbone-2.2.0-py2.7.egg/wishbone/lookup/__init__.py", line 199, in __init__
    self.wordlist = self.readWordlist()
  File "/home/smetj/data/python/virtualenv/wishbone/lib/python2.7/site-packages/wishbone-2.2.0-py2.7.egg/wishbone/lookup/__init__.py", line 202, in readWordlist
    with open("%s/../data/wordlist.txt" % (os.path.dirname(__file__)), encoding="utf8") as f:
TypeError: 'encoding' is an invalid keyword argument for this function

```

**Comment by smetj** [comment]
solved latest dev
